(cl:defpackage common_srvs-srv
  (:use )
  (:export
   "LOAD_OR_SAVE_GLOBAL_MAP"
   "<LOAD_OR_SAVE_GLOBAL_MAP-REQUEST>"
   "LOAD_OR_SAVE_GLOBAL_MAP-REQUEST"
   "<LOAD_OR_SAVE_GLOBAL_MAP-RESPONSE>"
   "LOAD_OR_SAVE_GLOBAL_MAP-RESPONSE"
   "RESET_ENV"
   "<RESET_ENV-REQUEST>"
   "RESET_ENV-REQUEST"
   "<RESET_ENV-RESPONSE>"
   "RESET_ENV-RESPONSE"
   "SET_INIT_POSE"
   "<SET_INIT_POSE-REQUEST>"
   "SET_INIT_POSE-REQUEST"
   "<SET_INIT_POSE-RESPONSE>"
   "SET_INIT_POSE-RESPONSE"
   "TRAJ_RECORD"
   "<TRAJ_RECORD-REQUEST>"
   "TRAJ_RECORD-REQUEST"
   "<TRAJ_RECORD-RESPONSE>"
   "TRAJ_RECORD-RESPONSE"
  ))

