// Generated by gencpp from file common_srvs/load_or_save_global_map.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAP_H
#define COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAP_H

#include <ros/service_traits.h>


#include <common_srvs/load_or_save_global_mapRequest.h>
#include <common_srvs/load_or_save_global_mapResponse.h>


namespace common_srvs
{

struct load_or_save_global_map
{

typedef load_or_save_global_mapRequest Request;
typedef load_or_save_global_mapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct load_or_save_global_map
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::load_or_save_global_map > {
  static const char* value()
  {
    return "f6daaba025bb906f289cd65773c2899f";
  }

  static const char* value(const ::common_srvs::load_or_save_global_map&) { return value(); }
};

template<>
struct DataType< ::common_srvs::load_or_save_global_map > {
  static const char* value()
  {
    return "common_srvs/load_or_save_global_map";
  }

  static const char* value(const ::common_srvs::load_or_save_global_map&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::load_or_save_global_mapRequest> should match
// service_traits::MD5Sum< ::common_srvs::load_or_save_global_map >
template<>
struct MD5Sum< ::common_srvs::load_or_save_global_mapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::load_or_save_global_map >::value();
  }
  static const char* value(const ::common_srvs::load_or_save_global_mapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::load_or_save_global_mapRequest> should match
// service_traits::DataType< ::common_srvs::load_or_save_global_map >
template<>
struct DataType< ::common_srvs::load_or_save_global_mapRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::load_or_save_global_map >::value();
  }
  static const char* value(const ::common_srvs::load_or_save_global_mapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::load_or_save_global_mapResponse> should match
// service_traits::MD5Sum< ::common_srvs::load_or_save_global_map >
template<>
struct MD5Sum< ::common_srvs::load_or_save_global_mapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::load_or_save_global_map >::value();
  }
  static const char* value(const ::common_srvs::load_or_save_global_mapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::load_or_save_global_mapResponse> should match
// service_traits::DataType< ::common_srvs::load_or_save_global_map >
template<>
struct DataType< ::common_srvs::load_or_save_global_mapResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::load_or_save_global_map >::value();
  }
  static const char* value(const ::common_srvs::load_or_save_global_mapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAP_H
