// Generated by gencpp from file common_srvs/load_or_save_global_mapRequest.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAPREQUEST_H
#define COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_srvs
{
template <class ContainerAllocator>
struct load_or_save_global_mapRequest_
{
  typedef load_or_save_global_mapRequest_<ContainerAllocator> Type;

  load_or_save_global_mapRequest_()
    : load_or_save(0)
    , file_name()  {
    }
  load_or_save_global_mapRequest_(const ContainerAllocator& _alloc)
    : load_or_save(0)
    , file_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _load_or_save_type;
  _load_or_save_type load_or_save;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct load_or_save_global_mapRequest_

typedef ::common_srvs::load_or_save_global_mapRequest_<std::allocator<void> > load_or_save_global_mapRequest;

typedef boost::shared_ptr< ::common_srvs::load_or_save_global_mapRequest > load_or_save_global_mapRequestPtr;
typedef boost::shared_ptr< ::common_srvs::load_or_save_global_mapRequest const> load_or_save_global_mapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator1> & lhs, const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.load_or_save == rhs.load_or_save &&
    lhs.file_name == rhs.file_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator1> & lhs, const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eafda46c8aeb89b9f0c6ffc09f6a1b43";
  }

  static const char* value(const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeafda46c8aeb89b9ULL;
  static const uint64_t static_value2 = 0xf0c6ffc09f6a1b43ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_srvs/load_or_save_global_mapRequest";
  }

  static const char* value(const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 load_or_save\n"
"string file_name\n"
;
  }

  static const char* value(const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.load_or_save);
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct load_or_save_global_mapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_srvs::load_or_save_global_mapRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "load_or_save: ";
    Printer<int32_t>::stream(s, indent + "  ", v.load_or_save);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_LOAD_OR_SAVE_GLOBAL_MAPREQUEST_H
