// Generated by gencpp from file common_srvs/reset_env.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_RESET_ENV_H
#define COMMON_SRVS_MESSAGE_RESET_ENV_H

#include <ros/service_traits.h>


#include <common_srvs/reset_envRequest.h>
#include <common_srvs/reset_envResponse.h>


namespace common_srvs
{

struct reset_env
{

typedef reset_envRequest Request;
typedef reset_envResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_env
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::reset_env > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::common_srvs::reset_env&) { return value(); }
};

template<>
struct DataType< ::common_srvs::reset_env > {
  static const char* value()
  {
    return "common_srvs/reset_env";
  }

  static const char* value(const ::common_srvs::reset_env&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::reset_envRequest> should match
// service_traits::MD5Sum< ::common_srvs::reset_env >
template<>
struct MD5Sum< ::common_srvs::reset_envRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::reset_env >::value();
  }
  static const char* value(const ::common_srvs::reset_envRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::reset_envRequest> should match
// service_traits::DataType< ::common_srvs::reset_env >
template<>
struct DataType< ::common_srvs::reset_envRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::reset_env >::value();
  }
  static const char* value(const ::common_srvs::reset_envRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::reset_envResponse> should match
// service_traits::MD5Sum< ::common_srvs::reset_env >
template<>
struct MD5Sum< ::common_srvs::reset_envResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::reset_env >::value();
  }
  static const char* value(const ::common_srvs::reset_envResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::reset_envResponse> should match
// service_traits::DataType< ::common_srvs::reset_env >
template<>
struct DataType< ::common_srvs::reset_envResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::reset_env >::value();
  }
  static const char* value(const ::common_srvs::reset_envResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_RESET_ENV_H
