// Generated by gencpp from file common_srvs/reset_envRequest.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_RESET_ENVREQUEST_H
#define COMMON_SRVS_MESSAGE_RESET_ENVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_srvs
{
template <class ContainerAllocator>
struct reset_envRequest_
{
  typedef reset_envRequest_<ContainerAllocator> Type;

  reset_envRequest_()
    {
    }
  reset_envRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::common_srvs::reset_envRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_srvs::reset_envRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_envRequest_

typedef ::common_srvs::reset_envRequest_<std::allocator<void> > reset_envRequest;

typedef boost::shared_ptr< ::common_srvs::reset_envRequest > reset_envRequestPtr;
typedef boost::shared_ptr< ::common_srvs::reset_envRequest const> reset_envRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_srvs::reset_envRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_srvs::reset_envRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace common_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_srvs::reset_envRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_srvs::reset_envRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::reset_envRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::reset_envRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::reset_envRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::reset_envRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_srvs::reset_envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::common_srvs::reset_envRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::common_srvs::reset_envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_srvs/reset_envRequest";
  }

  static const char* value(const ::common_srvs::reset_envRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_srvs::reset_envRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::common_srvs::reset_envRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_srvs::reset_envRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_envRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_srvs::reset_envRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::common_srvs::reset_envRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_RESET_ENVREQUEST_H
