// Generated by gencpp from file common_srvs/set_init_poseResponse.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_SET_INIT_POSERESPONSE_H
#define COMMON_SRVS_MESSAGE_SET_INIT_POSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_srvs
{
template <class ContainerAllocator>
struct set_init_poseResponse_
{
  typedef set_init_poseResponse_<ContainerAllocator> Type;

  set_init_poseResponse_()
    : success(false)  {
    }
  set_init_poseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::common_srvs::set_init_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_srvs::set_init_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_init_poseResponse_

typedef ::common_srvs::set_init_poseResponse_<std::allocator<void> > set_init_poseResponse;

typedef boost::shared_ptr< ::common_srvs::set_init_poseResponse > set_init_poseResponsePtr;
typedef boost::shared_ptr< ::common_srvs::set_init_poseResponse const> set_init_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_srvs::set_init_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_srvs::set_init_poseResponse_<ContainerAllocator1> & lhs, const ::common_srvs::set_init_poseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_srvs::set_init_poseResponse_<ContainerAllocator1> & lhs, const ::common_srvs::set_init_poseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_srvs::set_init_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::set_init_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::set_init_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::common_srvs::set_init_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_srvs/set_init_poseResponse";
  }

  static const char* value(const ::common_srvs::set_init_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"\n"
;
  }

  static const char* value(const ::common_srvs::set_init_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_init_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_srvs::set_init_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_srvs::set_init_poseResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_SET_INIT_POSERESPONSE_H
