// Generated by gencpp from file common_srvs/set_init_poseRequest.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_SET_INIT_POSEREQUEST_H
#define COMMON_SRVS_MESSAGE_SET_INIT_POSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_srvs
{
template <class ContainerAllocator>
struct set_init_poseRequest_
{
  typedef set_init_poseRequest_<ContainerAllocator> Type;

  set_init_poseRequest_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  set_init_poseRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::common_srvs::set_init_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_srvs::set_init_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_init_poseRequest_

typedef ::common_srvs::set_init_poseRequest_<std::allocator<void> > set_init_poseRequest;

typedef boost::shared_ptr< ::common_srvs::set_init_poseRequest > set_init_poseRequestPtr;
typedef boost::shared_ptr< ::common_srvs::set_init_poseRequest const> set_init_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_srvs::set_init_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_srvs::set_init_poseRequest_<ContainerAllocator1> & lhs, const ::common_srvs::set_init_poseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_srvs::set_init_poseRequest_<ContainerAllocator1> & lhs, const ::common_srvs::set_init_poseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_srvs::set_init_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::set_init_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::set_init_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71344c0ba01936756dc45bcd89ef437";
  }

  static const char* value(const ::common_srvs::set_init_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71344c0ba019367ULL;
  static const uint64_t static_value2 = 0x56dc45bcd89ef437ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_srvs/set_init_poseRequest";
  }

  static const char* value(const ::common_srvs::set_init_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 yaw #角度制\n"
;
  }

  static const char* value(const ::common_srvs::set_init_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_init_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_srvs::set_init_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_srvs::set_init_poseRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_SET_INIT_POSEREQUEST_H
