// Generated by gencpp from file common_srvs/set_init_pose.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_SET_INIT_POSE_H
#define COMMON_SRVS_MESSAGE_SET_INIT_POSE_H

#include <ros/service_traits.h>


#include <common_srvs/set_init_poseRequest.h>
#include <common_srvs/set_init_poseResponse.h>


namespace common_srvs
{

struct set_init_pose
{

typedef set_init_poseRequest Request;
typedef set_init_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_init_pose
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::set_init_pose > {
  static const char* value()
  {
    return "8ef2b8a88b01304a412aed45ca8dce40";
  }

  static const char* value(const ::common_srvs::set_init_pose&) { return value(); }
};

template<>
struct DataType< ::common_srvs::set_init_pose > {
  static const char* value()
  {
    return "common_srvs/set_init_pose";
  }

  static const char* value(const ::common_srvs::set_init_pose&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::set_init_poseRequest> should match
// service_traits::MD5Sum< ::common_srvs::set_init_pose >
template<>
struct MD5Sum< ::common_srvs::set_init_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::set_init_pose >::value();
  }
  static const char* value(const ::common_srvs::set_init_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::set_init_poseRequest> should match
// service_traits::DataType< ::common_srvs::set_init_pose >
template<>
struct DataType< ::common_srvs::set_init_poseRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::set_init_pose >::value();
  }
  static const char* value(const ::common_srvs::set_init_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::set_init_poseResponse> should match
// service_traits::MD5Sum< ::common_srvs::set_init_pose >
template<>
struct MD5Sum< ::common_srvs::set_init_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::set_init_pose >::value();
  }
  static const char* value(const ::common_srvs::set_init_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::set_init_poseResponse> should match
// service_traits::DataType< ::common_srvs::set_init_pose >
template<>
struct DataType< ::common_srvs::set_init_poseResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::set_init_pose >::value();
  }
  static const char* value(const ::common_srvs::set_init_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_SET_INIT_POSE_H
