// Generated by gencpp from file common_srvs/traj_recordRequest.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_TRAJ_RECORDREQUEST_H
#define COMMON_SRVS_MESSAGE_TRAJ_RECORDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace common_srvs
{
template <class ContainerAllocator>
struct traj_recordRequest_
{
  typedef traj_recordRequest_<ContainerAllocator> Type;

  traj_recordRequest_()
    : start_record(false)  {
    }
  traj_recordRequest_(const ContainerAllocator& _alloc)
    : start_record(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_record_type;
  _start_record_type start_record;





  typedef boost::shared_ptr< ::common_srvs::traj_recordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common_srvs::traj_recordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct traj_recordRequest_

typedef ::common_srvs::traj_recordRequest_<std::allocator<void> > traj_recordRequest;

typedef boost::shared_ptr< ::common_srvs::traj_recordRequest > traj_recordRequestPtr;
typedef boost::shared_ptr< ::common_srvs::traj_recordRequest const> traj_recordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common_srvs::traj_recordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common_srvs::traj_recordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common_srvs::traj_recordRequest_<ContainerAllocator1> & lhs, const ::common_srvs::traj_recordRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start_record == rhs.start_record;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common_srvs::traj_recordRequest_<ContainerAllocator1> & lhs, const ::common_srvs::traj_recordRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common_srvs::traj_recordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common_srvs::traj_recordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common_srvs::traj_recordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c551cd6959dd813268df5ef6a8546b2";
  }

  static const char* value(const ::common_srvs::traj_recordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c551cd6959dd813ULL;
  static const uint64_t static_value2 = 0x268df5ef6a8546b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common_srvs/traj_recordRequest";
  }

  static const char* value(const ::common_srvs::traj_recordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start_record\n"
;
  }

  static const char* value(const ::common_srvs::traj_recordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_record);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traj_recordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common_srvs::traj_recordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common_srvs::traj_recordRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "start_record: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_record);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_TRAJ_RECORDREQUEST_H
