// Generated by gencpp from file common_srvs/traj_record.msg
// DO NOT EDIT!


#ifndef COMMON_SRVS_MESSAGE_TRAJ_RECORD_H
#define COMMON_SRVS_MESSAGE_TRAJ_RECORD_H

#include <ros/service_traits.h>


#include <common_srvs/traj_recordRequest.h>
#include <common_srvs/traj_recordResponse.h>


namespace common_srvs
{

struct traj_record
{

typedef traj_recordRequest Request;
typedef traj_recordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct traj_record
} // namespace common_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::common_srvs::traj_record > {
  static const char* value()
  {
    return "1fcb5c5e47d363e693348dc6db88277b";
  }

  static const char* value(const ::common_srvs::traj_record&) { return value(); }
};

template<>
struct DataType< ::common_srvs::traj_record > {
  static const char* value()
  {
    return "common_srvs/traj_record";
  }

  static const char* value(const ::common_srvs::traj_record&) { return value(); }
};


// service_traits::MD5Sum< ::common_srvs::traj_recordRequest> should match
// service_traits::MD5Sum< ::common_srvs::traj_record >
template<>
struct MD5Sum< ::common_srvs::traj_recordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::traj_record >::value();
  }
  static const char* value(const ::common_srvs::traj_recordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::traj_recordRequest> should match
// service_traits::DataType< ::common_srvs::traj_record >
template<>
struct DataType< ::common_srvs::traj_recordRequest>
{
  static const char* value()
  {
    return DataType< ::common_srvs::traj_record >::value();
  }
  static const char* value(const ::common_srvs::traj_recordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::common_srvs::traj_recordResponse> should match
// service_traits::MD5Sum< ::common_srvs::traj_record >
template<>
struct MD5Sum< ::common_srvs::traj_recordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::common_srvs::traj_record >::value();
  }
  static const char* value(const ::common_srvs::traj_recordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::common_srvs::traj_recordResponse> should match
// service_traits::DataType< ::common_srvs::traj_record >
template<>
struct DataType< ::common_srvs::traj_recordResponse>
{
  static const char* value()
  {
    return DataType< ::common_srvs::traj_record >::value();
  }
  static const char* value(const ::common_srvs::traj_recordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMMON_SRVS_MESSAGE_TRAJ_RECORD_H
